[package]
name = "chameleon-macro"
version = "0.1.0"
authors = ["Andrew Jones <ascjones@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
core = { version = "0.1", package = "chameleon-core", path = "../core" }

