[package]
name = "chameleon-core"
version = "0.1.0"
authors = ["Andrew Jones <ascjones@gmail.com>"]
edition = "2018"

[dependencies]
frame-metadata = { path = "../../paritytech/frame-metadata/frame-metadata", default-features = false }
proc-macro2 = "1.0"
quote = "1"
syn = { version = "1.0", features = ["parsing", "full"] }
scale = { package = "parity-scale-codec", version = "1.3", default-features = false}
scale-info = { path = "../../paritytech/scale-info", package = "scale-info", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
    "frame-metadata/std",
    "scale/std",
    "scale-info/std",
]
